version: "3"
services:
  docs:
    restart: always
    image:  sujaykumarh/docsify:latest
    ports:
      - 3000:3000
    working_dir: /docs
    networks:
      - mgmt
    volumes:
      # replace with your own path  "xxxx:/docs"
      - "/home/workspace/project/kiga-doc:/docs"
    command: serve

networks:
  mgmt: 
